version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - mkdir -p $CONTAINER_NAME/DO_shiny
      - git clone https://github.com/pjpalla/DO_shiny.git $CONTAINER_NAME/DO_shiny
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $REPOSITORY_URI:latest $CONTAINER_NAME 
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$CONTAINER_NAME 
      ## $REPOSITORY_URI:$IMAGE_TAG  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      # - docker push $REPOSITORY_URI:latest
      # - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:$CONTAINER_NAME
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI:$CONTAINER_NAME > imagedefinitions.json
artifacts:
    files: imagedefinitions.json